// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {deploy} from '../models';

export function AddAliyunCredential(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddBlackSegment(arg1:string,arg2:string):Promise<void>;

export function AddGCPCredentialADC(arg1:string,arg2:string):Promise<string>;

export function AddGCPCredentialGcloud(arg1:string):Promise<string>;

export function AddGCPCredentialOAuth(arg1:string,arg2:string):Promise<string>;

export function AddGCPCredentialServiceAccount(arg1:string,arg2:string):Promise<string>;

export function BatchDelete(arg1:string,arg2:Array<string>):Promise<number>;

export function BatchSetPTR(arg1:Array<string>):Promise<string>;

export function CancelBatch(arg1:string):Promise<void>;

export function CheckGCPADC():Promise<string>;

export function CheckIPBlackSegment(arg1:string):Promise<Record<string, string>>;

export function CleanupOrphanResources():Promise<main.OrphanCleanupReport>;

export function ClearDNSBLCache():Promise<number>;

export function DeleteAliyunCredential(arg1:string):Promise<void>;

export function DeleteGCPCredential(arg1:string):Promise<void>;

export function DeletePersona(arg1:string):Promise<void>;

export function DeleteVPSTemplate(arg1:string):Promise<void>;

export function DiagnoseKumoMTA(arg1:string):Promise<main.KumoMTADiagnosticDTO>;

export function ExportPersonasJSON():Promise<string>;

export function ExportSMTP(arg1:string):Promise<string>;

export function ExtractFromVPS(arg1:Array<string>):Promise<main.ExtractSummary>;

export function ExtractFromVPSForceType(arg1:Array<string>,arg2:boolean,arg3:string):Promise<main.ExtractSummary>;

export function ExtractFromVPSWithDelete(arg1:Array<string>,arg2:boolean):Promise<main.ExtractSummary>;

export function FixMailNodeTag(arg1:Array<string>):Promise<number>;

export function GetBatchLogs(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetBatchProgress(arg1:string):Promise<deploy.BatchProgress>;

export function GetExtractOutputDir():Promise<string>;

export function GetExtractSchedule():Promise<main.ExtractScheduleConfig>;

export function GetGCPMonitorReport(arg1:string,arg2:number,arg3:main.GCPMonitorPricing):Promise<main.GCPMonitorReport>;

export function GetSSHPrivateKey():Promise<string>;

export function GetSSHPrivateKeyPath():Promise<string>;

export function GetSSHPublicKey():Promise<string>;

export function GetServerStatus(arg1:string,arg2:number):Promise<main.ServerStatusDTO>;

export function GetVersion():Promise<string>;

export function ImportBlackSegmentsText(arg1:string):Promise<Record<string, any>>;

export function ListAliyunCredentials():Promise<Array<main.AliyunCredentialDTO>>;

export function ListBatches():Promise<Array<main.BatchTaskDTO>>;

export function ListBlackSegments():Promise<Array<main.BlackSegmentDTO>>;

export function ListDNSRecords():Promise<Array<main.DNSRecordDTO>>;

export function ListGCPCredentials():Promise<Array<main.GCPCredentialDTO>>;

export function ListPersonas():Promise<Array<main.PersonaDTO>>;

export function ListStaticIPs():Promise<Array<main.StaticIPDTO>>;

export function ListVPS():Promise<Array<main.VPSInstanceDTO>>;

export function ListVPSTemplates():Promise<Array<main.VPSTemplateDTO>>;

export function OpenLogDir():Promise<void>;

export function PruneBatchIPs(arg1:string,arg2:Array<string>):Promise<number>;

export function RemoveBlackSegment(arg1:number):Promise<void>;

export function RepairBatchPTR(arg1:Array<string>):Promise<string>;

export function SavePersona(arg1:main.PersonaDTO):Promise<string>;

export function SaveVPSTemplate(arg1:main.VPSTemplateDTO):Promise<string>;

export function SetAliyunCredentialEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetExtractSchedule(arg1:main.ExtractScheduleConfig):Promise<void>;

export function SetGCPCredentialEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartBatch(arg1:deploy.BatchRequest):Promise<string>;

export function StartMTADeploy(arg1:Array<string>,arg2:deploy.DeployOpts):Promise<string>;

export function StartStageA(arg1:deploy.StageARequest):Promise<string>;

export function StartStageB(arg1:string,arg2:deploy.StageBRequest):Promise<void>;

export function StartStageC(arg1:deploy.StageCRequest):Promise<string>;

export function TestAliyunCredential(arg1:string):Promise<string>;

export function TestGCPCredential(arg1:string):Promise<string>;
