// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAliyunCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAliyunCredential'](arg1, arg2, arg3);
}

export function AddBlackSegment(arg1, arg2) {
  return window['go']['main']['App']['AddBlackSegment'](arg1, arg2);
}

export function AddGCPCredentialADC(arg1, arg2) {
  return window['go']['main']['App']['AddGCPCredentialADC'](arg1, arg2);
}

export function AddGCPCredentialGcloud(arg1) {
  return window['go']['main']['App']['AddGCPCredentialGcloud'](arg1);
}

export function AddGCPCredentialOAuth(arg1, arg2) {
  return window['go']['main']['App']['AddGCPCredentialOAuth'](arg1, arg2);
}

export function AddGCPCredentialServiceAccount(arg1, arg2) {
  return window['go']['main']['App']['AddGCPCredentialServiceAccount'](arg1, arg2);
}

export function BatchDelete(arg1, arg2) {
  return window['go']['main']['App']['BatchDelete'](arg1, arg2);
}

export function BatchSetPTR(arg1) {
  return window['go']['main']['App']['BatchSetPTR'](arg1);
}

export function CancelBatch(arg1) {
  return window['go']['main']['App']['CancelBatch'](arg1);
}

export function CheckGCPADC() {
  return window['go']['main']['App']['CheckGCPADC']();
}

export function CheckIPBlackSegment(arg1) {
  return window['go']['main']['App']['CheckIPBlackSegment'](arg1);
}

export function CleanupOrphanResources() {
  return window['go']['main']['App']['CleanupOrphanResources']();
}

export function ClearDNSBLCache() {
  return window['go']['main']['App']['ClearDNSBLCache']();
}

export function DeleteAliyunCredential(arg1) {
  return window['go']['main']['App']['DeleteAliyunCredential'](arg1);
}

export function DeleteGCPCredential(arg1) {
  return window['go']['main']['App']['DeleteGCPCredential'](arg1);
}

export function DeletePersona(arg1) {
  return window['go']['main']['App']['DeletePersona'](arg1);
}

export function DeleteVPSTemplate(arg1) {
  return window['go']['main']['App']['DeleteVPSTemplate'](arg1);
}

export function DiagnoseKumoMTA(arg1) {
  return window['go']['main']['App']['DiagnoseKumoMTA'](arg1);
}

export function ExportPersonasJSON() {
  return window['go']['main']['App']['ExportPersonasJSON']();
}

export function ExportSMTP(arg1) {
  return window['go']['main']['App']['ExportSMTP'](arg1);
}

export function ExtractFromVPS(arg1) {
  return window['go']['main']['App']['ExtractFromVPS'](arg1);
}

export function ExtractFromVPSForceType(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractFromVPSForceType'](arg1, arg2, arg3);
}

export function ExtractFromVPSWithDelete(arg1, arg2) {
  return window['go']['main']['App']['ExtractFromVPSWithDelete'](arg1, arg2);
}

export function FixMailNodeTag(arg1) {
  return window['go']['main']['App']['FixMailNodeTag'](arg1);
}

export function GetBatchLogs(arg1, arg2) {
  return window['go']['main']['App']['GetBatchLogs'](arg1, arg2);
}

export function GetBatchProgress(arg1) {
  return window['go']['main']['App']['GetBatchProgress'](arg1);
}

export function GetExtractOutputDir() {
  return window['go']['main']['App']['GetExtractOutputDir']();
}

export function GetExtractSchedule() {
  return window['go']['main']['App']['GetExtractSchedule']();
}

export function GetGCPMonitorReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGCPMonitorReport'](arg1, arg2, arg3);
}

export function GetSSHPrivateKey() {
  return window['go']['main']['App']['GetSSHPrivateKey']();
}

export function GetSSHPrivateKeyPath() {
  return window['go']['main']['App']['GetSSHPrivateKeyPath']();
}

export function GetSSHPublicKey() {
  return window['go']['main']['App']['GetSSHPublicKey']();
}

export function GetServerStatus(arg1, arg2) {
  return window['go']['main']['App']['GetServerStatus'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportBlackSegmentsText(arg1) {
  return window['go']['main']['App']['ImportBlackSegmentsText'](arg1);
}

export function ListAliyunCredentials() {
  return window['go']['main']['App']['ListAliyunCredentials']();
}

export function ListBatches() {
  return window['go']['main']['App']['ListBatches']();
}

export function ListBlackSegments() {
  return window['go']['main']['App']['ListBlackSegments']();
}

export function ListDNSRecords() {
  return window['go']['main']['App']['ListDNSRecords']();
}

export function ListGCPCredentials() {
  return window['go']['main']['App']['ListGCPCredentials']();
}

export function ListPersonas() {
  return window['go']['main']['App']['ListPersonas']();
}

export function ListStaticIPs() {
  return window['go']['main']['App']['ListStaticIPs']();
}

export function ListVPS() {
  return window['go']['main']['App']['ListVPS']();
}

export function ListVPSTemplates() {
  return window['go']['main']['App']['ListVPSTemplates']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function PruneBatchIPs(arg1, arg2) {
  return window['go']['main']['App']['PruneBatchIPs'](arg1, arg2);
}

export function RemoveBlackSegment(arg1) {
  return window['go']['main']['App']['RemoveBlackSegment'](arg1);
}

export function RepairBatchPTR(arg1) {
  return window['go']['main']['App']['RepairBatchPTR'](arg1);
}

export function SavePersona(arg1) {
  return window['go']['main']['App']['SavePersona'](arg1);
}

export function SaveVPSTemplate(arg1) {
  return window['go']['main']['App']['SaveVPSTemplate'](arg1);
}

export function SetAliyunCredentialEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAliyunCredentialEnabled'](arg1, arg2);
}

export function SetExtractSchedule(arg1) {
  return window['go']['main']['App']['SetExtractSchedule'](arg1);
}

export function SetGCPCredentialEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetGCPCredentialEnabled'](arg1, arg2);
}

export function StartBatch(arg1) {
  return window['go']['main']['App']['StartBatch'](arg1);
}

export function StartMTADeploy(arg1, arg2) {
  return window['go']['main']['App']['StartMTADeploy'](arg1, arg2);
}

export function StartStageA(arg1) {
  return window['go']['main']['App']['StartStageA'](arg1);
}

export function StartStageB(arg1, arg2) {
  return window['go']['main']['App']['StartStageB'](arg1, arg2);
}

export function StartStageC(arg1) {
  return window['go']['main']['App']['StartStageC'](arg1);
}

export function TestAliyunCredential(arg1) {
  return window['go']['main']['App']['TestAliyunCredential'](arg1);
}

export function TestGCPCredential(arg1) {
  return window['go']['main']['App']['TestGCPCredential'](arg1);
}
